### ISSUE TITLE
GFM footnotes

### ISSUE THREAD

**Issue by ngnhat** [syntax-tree/hast-util-sanitize#30] opened 2023-10-25 02:22 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-sanitize": "^6.0.0"

### Link to runnable example

react-markdown

### Steps to reproduce

the `rehype-sanitize` has changed the id of the elements below:

```html
<a href="#user-content-fn-1" id="user-content-user-content-fnref-1" data-footnote-ref="true" aria-describedby="user-content-footnote-label">1</a>

...

<li id="user-content-user-content-fn-1">
<p>something...  <a href="#user-content-fnref-1" data-footnote-backref="" aria-label="Back to reference 1" class="data-footnote-backref">↩</a></p>
</li>
```

### Expected behavior

It should not be changed.

### Actual behavior

idk

### Affected runtime and version

node@18.2

**Comment by ChristianMurphy** [comment] 2023-10-25 02:27
Duplicate of https://github.com/syntax-tree/hast-util-sanitize/issues/29

**Closed by ChristianMurphy** 2023-10-25 02:27 UTC
Labels: 🤞 phase/open
